export enum LedgerTypeStrict {
  RIDE_PAYMENT = "RIDE_PAYMENT",
  PLATFORM_FEE = "PLATFORM_FEE",

  DRIVER_EARNING = "DRIVER_EARNING",
  DRIVER_PAYOUT = "DRIVER_PAYOUT",

  TOPUP = "TOPUP",
  WITHDRAWAL = "WITHDRAWAL",

  REFUND = "REFUND",
  REFUND_DEBIT = "REFUND_DEBIT",

  BOOKING_PAYMENT = "BOOKING_PAYMENT",
  BOOKING_RESERVE = "BOOKING_RESERVE",

  PROMO = "PROMO",
  ADJUSTMENT = "ADJUSTMENT",
}
